name: CI
on:
  push:  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Collect Texlive
        run: ./windows.ps1
        
      - name: Install Manim And Test
        run: |
          Get-ChildItem "$PWD\ManimTex" | Measure-Object -Property Length -sum
          choco install --no-progress manim
          $env:Path += ";" + "$($PWD)\ManimTex\bin\win32"
          Start-Process -ArgumentList "path add" -FilePath "$($PWD)\ManimTex\bin\win32\tlmgr.bat" -NoNewWindow -Wait
          curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
          manim tex.py
      - uses: actions/upload-artifact@v2
        with:
         name: ManimTex
         path: ManimTex
      - uses: actions/upload-artifact@v2
        with:
         name: manimtest
         path: media
