name: CI
on:
  push:  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        
      - name: Download Texlive for Windows
        if: runner.os == 'Windows'
        run: |
          ./windows.ps1
          7a a ManimTex.zip "$($PWD)ManimTex"
      - name: Download Texline for Linux
        if: runner.os != 'Windows'
        run: |
          sh linux.sh
      - name: Pack Tex Mac
        if: runner.os == 'macos'
        run: |
          tar zcf ManimTex.tar.gz -C ~/Library TinyTeX
      - name: Pack Tex Linux
        if: runner.os == 'linux'
        run: |
          tar zcf ManimTex.tar.gz -C ~ .TinyTeX
      - name: Install Manim And Test on Windows
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem "$PWD\ManimTex" | Measure-Object -Property Length -sum
          choco install --no-progress manim
          $env:Path += ";" + "$($PWD)\ManimTex\bin\win32"
          Start-Process -ArgumentList "path add" -FilePath "$($PWD)\ManimTex\bin\win32\tlmgr.bat" -NoNewWindow -Wait
          curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
          manim tex.py
      - uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
         name: ManimTex
         path: ManimTex.zip
      - uses: actions/upload-artifact@v2
        if: runner.os != 'Windows'
        with:
         name: ManimTex.${{ matrix.os }}.tar.gz
         path: ManimTex.tar.gz
      - uses: actions/upload-artifact@v2
        with:
         name: manimtest
         path: media
