name: Build Tex for Manim
on:
  push:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8       
      - name: Download Texlive for Windows
        if: runner.os == 'Windows'
        run: |
          ./windows.ps1
          7z a ManimTex.zip "$($PWD)\ManimTex"
      - name: Download Texlive for Linux
        if: runner.os != 'Windows'
        run: |
          sh linux.sh
          export PATH="$HOME/bin:$PATH"
          ls $HOME/bin
          echo "::set-env name=PATH::${PATH}"

      - name: Pack Tex Mac
        if: runner.os == 'macos'
        run: |
          tar zcf ManimTex.tar.gz -C ~/Library ManimTex
      - name: Pack Tex Linux
        if: runner.os == 'linux'
        run: |
          tar zcf ManimTex.tar.gz -C ~ ManimTex
      - name: Install Manim And Test on Windows
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem "$PWD\ManimTex" | Measure-Object -Property Length -sum
          choco install --no-progress manim
          $env:Path += ";" + "$($PWD)\ManimTex\bin\win32"
          Start-Process -ArgumentList "path add" -FilePath "$($PWD)\ManimTex\bin\win32\tlmgr.bat" -NoNewWindow -Wait
          python -m pip install https://github.com/ManimCommunity/manim/archive/master.zip
          curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
          python -m manim tex.py

      - name: Install Manim and Test Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install https://github.com/ManimCommunity/manim/archive/master.zip
          curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
          manim tex.py
      - name: Install Manim and Test MacOS
        if: runner.os == 'macOS'
        run: |
          brew install openssl readline ffmpeg sox pyenv pyenv-virtualenv
          pip install https://github.com/ManimCommunity/manim/archive/master.zip
          curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
          manim tex.py

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
         name: ManimTex-${{ runner.os }}.zip
         path: ManimTex.zip
      - uses: actions/upload-artifact@v2
        if: runner.os != 'Windows'
        with:
         name: ManimTex-${{ runner.os }}.tar.gz
         path: ManimTex.tar.gz
      - uses: actions/upload-artifact@v2
        with:
         name: manimtest
         path: media


